#########
###
GET http://localhost:8090/api/v1/nodes/find?title=Lorem ipsum

###
POST http://localhost:8090/api/v1/nodes
Content-Type: application/json

{
  "title": "Lorem Lorem",
  "contentText": "Lorem ipsum dolor Lorem ipsum dolor"
}

###
GET http://localhost:8090/api/v1/nodes/find?title=Lorem Lorem

###
POST http://localhost:8090/api/v1/nodes
Content-Type: application/json

{
  "title": "Lorem Empty Content"
}

###
GET http://localhost:8090/api/v1/nodes/find?title=Lorem Empty Content

###
POST http://localhost:8090/api/v1/nodes
Content-Type: application/json

{
  "title": "",
  "contentText": "Lorem ipsum dolor Empty Title"
}

###
GET http://localhost:8090/api/v1/nodes/find?title=

###
PATCH http://localhost:8090/api/v1/nodes
Content-Type: application/json

{
  "id": "notExistingId",
  "title": "Lorem 000",
  "contentText": "Lorem ipsum dolor"
}

###
GET http://localhost:8090/api/v1/nodes/find?title=Lorem Empty Content

###
PATCH http://localhost:8090/api/v1/nodes
Content-Type: application/json

{
  "id": "018d6fde-64fb-772c-9354-acdeed56c48d",
  "title": "Lorem NEW",
  "contentText": "Lorem ipsum dolor NEW"
}

###
GET http://localhost:8090/api/v1/nodes/018d6fde-64fb-772c-9354-acdeed56c48d

###
GET http://localhost:8090/api/v1/nodes/find?title=Lorem NEW

###
GET http://localhost:8090/api/v1/nodes/018d6fd9-138b-754b-aaa2-7c47b8774bf6

###
GET http://localhost:8090/api/v1/nodes/

###
DELETE http://localhost:8090/api/v1/nodes/018d6fde-64fb-772c-9354-acdeed56c48d

###
GET http://localhost:8090/api/v1/nodes/018d6fde-64fb-772c-9354-acdeed56c48d

###
GET http://localhost:8090/api/v1/nodes/find

###
GET http://localhost:8090/api/v1/nodes/find?title=NotExistingTitle


